jobs:

- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda env create --file environment.yaml
    displayName: Setup conda environment

  - script: |
      source activate ntstat
      export CFLAGS="$CFLAGS $(python3-config --cflags)"
      export LDFLAGS="$LDFLAGS $(python3-config --ldflags)"
      meson setup build
      meson install -C build
    displayName: Compile ntStat
