jobs:

- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'

  - script: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda env create --file environment.yaml
    displayName: Setup environment

  - script: |
      source activate ntstat
      ls $CONDA_PREFIX/include/python3.1*
      echo $CFLAGS
      echo $CXXFLAGS
      echo $C_INCLUDE_FLAGS
      echo $CPLUS_INCLUDE_FLAGS
      pybind11-config --includes
      python3-config --cflags
      python3-config --ldflags
    displayName: Debug

  - script: |
      source activate ntstat
      meson setup -Dpython.install_env=auto --prefix=$CONDA_PREFIX build
      meson install -C build
    displayName: Compile ntStat
