jobs:

- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true

  - script: |
      echo "##vso[task.prependpath]$CONDA/bin"
      conda env create --file environment.yaml
    displayName: Setup environment

  - script: |
      source activate ntstat
      meson setup --prefix=$CONDA_PREFIX build
      meson install -C build
    displayName: Compile ntStat
  
  - script: |
      source activate ntstat
      python -m unittest discover -s tests
    displayName: Run tests