name: ntstat
channels:
  - bioconda
  - conda-forge
dependencies:
  - compilers
  - meson
  - meson-python
  - cmake
  - btllib>=1.7.2
  - cpp-argparse
  - cpp-tabulate
  - indicators
  - kneed
  - matplotlib
  - numpy
  - pandas
  - pybind11
  - python
  - scikit-image
  - scikit-learn
  - scipy
  - tabulate
  - tqdm
