name: ntstat
channels:
  - bioconda
  - conda-forge
dependencies:
  - compilers
  - meson
  - btllib>=1.7.2
  - cpp-argparse
  - cpp-tabulate
  - kneed
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tabulate
  - tqdm
