name: ntstat
channels:
  - bioconda
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - btllib>=1.7.2
  - cpp-argparse
  - cpp-tabulate
  - cpython
  - kneed
  - matplotlib
  - numpy
  - pandas
  - pybind11
  - python
  - python-devtools
  - scikit-learn
  - scipy
  - tabulate
  - tqdm
