name: ntstat
channels:
  - bioconda
  - conda-forge
dependencies:
  - compilers
  - python
  - meson
  - meson-python
  - cmake
  - btllib>=1.7.2
  - cpp-argparse
  - cpp-tabulate
  - indicators
  - pybind11
  - matplotlib
  - numpy
  - scipy
  - tabulate
